### ISSUE TITLE
Uber documentation request

### ISSUE THREAD

**Issue by sophia-wright-blue** [pmin91/metis#1]
thanks for releasing this amazing repo @pmin91 ! The opinion mining project has a medium blog to go with it - I was wondering if you had any documentation for the Uber demand forecasting project? I'm mostly interested in your opinion of the choice between Prophet and LSTM (GRU), and the applicability of both. Thanks,

**Comment by pmin91** [comment]
@sophia-wright-blue Thanks! I'm glad you found it useful. You're right - I did not publish a blogpost on the Uber demand forecasting project, as I was unsure whether there would be a great deal of interest. My intuition for using an RNN model over Prophet was that Prophet is only able to utilize autocorrelation for one variable (although you could add extra regressors, it is a bit limiting), whereas an RNN model can take in a sequence of a large feature dimension (i.e. all 140 locations) as input as opposed to just a single dimension. There is also another limitation in that if you were to set the daily trend parameter as true, it will actually consider the trend to be consistent throughout every day of the week (when in reality, the trend between weekends and weekdays are vastly different if you do some EDA). There is one way to get around this, which is to assume that there is no daily trend, but nonetheless I wanted to explore an alternative to Prophet, and using an RNN model was a promising choice. Perhaps I will come back to documenting this after my crazy schedule calms down a bit, if I feel like it would be helpful for some. For now, let me know if my explanation made sense. Best,

**Comment by sophia-wright-blue** [comment]
Thanks for the detailed response @pmin91! Your explanation makes sense, and I look forward to understanding your code better - hopefully you'll find some time to add some documentation. Good luck!
